-- Create database tables for CRM entities

-- Leads table
CREATE TABLE IF NOT EXISTS leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    salutation VARCHAR(10),
    email VARCHAR(255),
    phone_number VARCHAR(20),
    mobile_phone VARCHAR(20),
    other_phone VARCHAR(20),
    verified_phone BOOLEAN DEFAULT FALSE,
    verified_email BOOLEAN DEFAULT FALSE,
    address TEXT,
    date_of_birth DATE,
    owner VARCHAR(100),
    current_status VARCHAR(50) DEFAULT 'Open',
    status_reason TEXT,
    current_progress VARCHAR(50),
    nac_process_stage VARCHAR(100),
    survey_status VARCHAR(100),
    survey_date DATE,
    survey_completed BOOLEAN DEFAULT FALSE,
    last_guide_sent TIMESTAMP,
    active_duration_days INTEGER DEFAULT 0,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    meeting_achievement TEXT,
    goals TEXT,
    budget DECIMAL(15,2),
    budget_frequency VARCHAR(20),
    goal_term VARCHAR(50),
    goal_year INTEGER,
    household_income DECIMAL(15,2),
    property_value DECIMAL(15,2),
    mortgage_value DECIMAL(15,2),
    savings_investments DECIMAL(15,2),
    pension_plans_value DECIMAL(15,2),
    car_value DECIMAL(15,2),
    contents_value DECIMAL(15,2),
    antiques_value DECIMAL(15,2),
    bat_value DECIMAL(15,2),
    life_insurance_value DECIMAL(15,2),
    other_assets_value DECIMAL(15,2),
    outstanding_mortgage DECIMAL(15,2),
    other_loans_value DECIMAL(15,2),
    other_liabilities_value DECIMAL(15,2),
    marital_status VARCHAR(20),
    number_of_children INTEGER,
    will_clause_effect TEXT,
    gifts_last_7_years BOOLEAN DEFAULT FALSE,
    gifting_10_percent_estate BOOLEAN DEFAULT FALSE,
    iht_score DECIMAL(10,2),
    nil_rate_band DECIMAL(15,2),
    type_of_lead VARCHAR(100),
    template_type VARCHAR(100),
    customer_type VARCHAR(100),
    lead_source VARCHAR(100),
    campaign_name VARCHAR(100),
    last_campaign_date DATE,
    marketing_materials_sent BOOLEAN DEFAULT FALSE,
    added_to_marketing_list BOOLEAN DEFAULT FALSE,
    preferred_contact_method VARCHAR(50),
    allow_email BOOLEAN DEFAULT TRUE,
    allow_phone BOOLEAN DEFAULT TRUE,
    allow_fax BOOLEAN DEFAULT FALSE,
    allow_mail BOOLEAN DEFAULT TRUE,
    allow_bulk_email BOOLEAN DEFAULT FALSE,
    notes TEXT,
    last_note_by VARCHAR(100),
    last_note_date TIMESTAMP,
    guides_sent TEXT,
    followup_letter_date DATE,
    followup_letter_name VARCHAR(100),
    followup_letter_notes TEXT
);

-- Contacts table
CREATE TABLE IF NOT EXISTS contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    salutation VARCHAR(10),
    email VARCHAR(255),
    mobile_phone VARCHAR(20),
    home_phone VARCHAR(20),
    business_phone VARCHAR(20),
    fax VARCHAR(20),
    owner VARCHAR(100),
    status VARCHAR(50) DEFAULT 'Active',
    status_reason TEXT,
    appointment_booked BOOLEAN DEFAULT FALSE,
    date_cancelled DATE,
    review_status VARCHAR(100),
    review_next_due_date DATE,
    review_actual_date DATE,
    review_next_step TEXT,
    review_outcome TEXT,
    reviewed_by VARCHAR(100),
    review_created_on TIMESTAMP,
    preferred_day VARCHAR(20),
    preferred_time VARCHAR(20),
    preferred_service VARCHAR(100),
    preferred_facility VARCHAR(100),
    preferred_user VARCHAR(100),
    allow_email BOOLEAN DEFAULT TRUE,
    allow_phone BOOLEAN DEFAULT TRUE,
    allow_fax BOOLEAN DEFAULT FALSE,
    allow_mail BOOLEAN DEFAULT TRUE,
    allow_bulk_email BOOLEAN DEFAULT FALSE,
    existing_survey_clarity TEXT,
    existing_survey_helpfulness TEXT,
    existing_survey_advisor_ability TEXT,
    existing_survey_standard TEXT,
    existing_survey_establishment TEXT,
    existing_survey_result VARCHAR(100),
    potential_survey_literature_useful BOOLEAN,
    potential_survey_advice_clear BOOLEAN,
    potential_survey_rushed BOOLEAN,
    potential_survey_feedback TEXT,
    potential_survey_did_not_go_ahead_reason TEXT,
    address_name VARCHAR(100),
    street_1 VARCHAR(100),
    street_2 VARCHAR(100),
    street_3 VARCHAR(100),
    city VARCHAR(50),
    county VARCHAR(50),
    postal_code VARCHAR(20),
    country VARCHAR(50),
    birthday DATE,
    anniversary DATE,
    gender VARCHAR(20),
    marital_status VARCHAR(20),
    spouse_partner_name VARCHAR(100),
    occupation VARCHAR(100),
    property_value DECIMAL(15,2),
    savings_investments DECIMAL(15,2),
    mortgage_value DECIMAL(15,2),
    total_current_value DECIMAL(15,2),
    out_of_cash BOOLEAN DEFAULT FALSE,
    phase_1_complete BOOLEAN DEFAULT FALSE,
    phase_2_complete BOOLEAN DEFAULT FALSE,
    phase_3_complete BOOLEAN DEFAULT FALSE,
    investment_service_status VARCHAR(50),
    investment_profile_date DATE,
    funds_switched BOOLEAN DEFAULT FALSE,
    fund_switch_status VARCHAR(100),
    mps_fee DECIMAL(10,2),
    mps_data_input BOOLEAN DEFAULT FALSE,
    osf_data_input BOOLEAN DEFAULT FALSE,
    originating_lead UUID REFERENCES leads(id),
    will_completed BOOLEAN DEFAULT FALSE,
    lpa_signed_by_donor BOOLEAN DEFAULT FALSE,
    lpa_completed BOOLEAN DEFAULT FALSE,
    presentation_consultation_notes TEXT,
    omw_profile_needed BOOLEAN DEFAULT FALSE,
    docu_sign_forms_required TEXT,
    docu_sign_sent BOOLEAN DEFAULT FALSE,
    email_to_info BOOLEAN DEFAULT FALSE,
    send_investment_program BOOLEAN DEFAULT FALSE,
    member_service_level VARCHAR(50),
    client_agreement_signed BOOLEAN DEFAULT FALSE,
    risk_level VARCHAR(20),
    supervising_financial_advisor VARCHAR(100),
    supporting_broker VARCHAR(100),
    seminar_invitation_sent BOOLEAN DEFAULT FALSE,
    seminar_invitation_date DATE,
    seminar_attended BOOLEAN DEFAULT FALSE,
    google_review_points INTEGER DEFAULT 0,
    trustpilot_points INTEGER DEFAULT 0,
    vouched_for_points INTEGER DEFAULT 0,
    claimed_points INTEGER DEFAULT 0,
    referral_source VARCHAR(100),
    customer_points_summary TEXT,
    notes TEXT,
    activities TEXT,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Opportunities table
CREATE TABLE IF NOT EXISTS opportunities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contact_id UUID REFERENCES contacts(id),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    stage VARCHAR(50) DEFAULT 'Prospecting',
    probability INTEGER DEFAULT 0,
    amount DECIMAL(15,2),
    expected_close_date DATE,
    owner VARCHAR(100),
    source VARCHAR(100),
    type VARCHAR(50),
    priority VARCHAR(20) DEFAULT 'Medium',
    status VARCHAR(50) DEFAULT 'Open',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_date DATE,
    notes TEXT
);

-- FactFinds table
CREATE TABLE IF NOT EXISTS factfinds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contact_id UUID REFERENCES contacts(id),
    factfind_date DATE,
    consultant_name VARCHAR(100),
    owner VARCHAR(100),
    contact_name VARCHAR(100),
    currency VARCHAR(10) DEFAULT 'GBP',
    reason_for_meeting TEXT,
    
    -- Client 1 Details
    c1_title VARCHAR(10),
    c1_first_name VARCHAR(50),
    c1_middle_name VARCHAR(50),
    c1_last_name VARCHAR(50),
    c1_other_names VARCHAR(100),
    c1_gender VARCHAR(20),
    c1_marital_status VARCHAR(20),
    c1_health_status VARCHAR(50),
    c1_employment_status VARCHAR(50),
    c1_occupation VARCHAR(100),
    c1_dob DATE,
    c1_smoker BOOLEAN DEFAULT FALSE,
    c1_nationality VARCHAR(50),
    c1_has_will BOOLEAN DEFAULT FALSE,
    c1_has_lpa BOOLEAN DEFAULT FALSE,
    c1_national_insurance VARCHAR(20),
    c1_id_type VARCHAR(50),
    c1_id_number VARCHAR(50),
    c1_id_country VARCHAR(50),
    c1_id_expiry DATE,
    c1_town_of_birth VARCHAR(100),
    
    -- Client 2 Details
    c2_title VARCHAR(10),
    c2_first_name VARCHAR(50),
    c2_middle_name VARCHAR(50),
    c2_last_name VARCHAR(50),
    c2_other_names VARCHAR(100),
    c2_gender VARCHAR(20),
    c2_marital_status VARCHAR(20),
    c2_health_status VARCHAR(50),
    c2_employment_status VARCHAR(50),
    c2_occupation VARCHAR(100),
    c2_dob DATE,
    c2_smoker BOOLEAN DEFAULT FALSE,
    c2_nationality VARCHAR(50),
    c2_has_will BOOLEAN DEFAULT FALSE,
    c2_has_lpa BOOLEAN DEFAULT FALSE,
    c2_national_insurance VARCHAR(20),
    c2_id_type VARCHAR(50),
    c2_id_number VARCHAR(50),
    c2_id_country VARCHAR(50),
    c2_id_expiry DATE,
    c2_town_of_birth VARCHAR(100),
    
    -- Income & Expenses (Client 1)
    c1_income DECIMAL(15,2),
    c1_council_tax DECIMAL(15,2),
    c1_utilities DECIMAL(15,2),
    c1_groceries DECIMAL(15,2),
    c1_insurances DECIMAL(15,2),
    c1_entertainment DECIMAL(15,2),
    c1_regular_commitments DECIMAL(15,2),
    c1_discretionary_spending DECIMAL(15,2),
    c1_mortgage_payments DECIMAL(15,2),
    c1_loans_or_credit_cards DECIMAL(15,2),
    c1_other_outgoings DECIMAL(15,2),
    c1_total_outgoings DECIMAL(15,2),
    
    -- Income & Expenses (Client 2)
    c2_income DECIMAL(15,2),
    c2_council_tax DECIMAL(15,2),
    c2_utilities DECIMAL(15,2),
    c2_groceries DECIMAL(15,2),
    c2_insurances DECIMAL(15,2),
    c2_entertainment DECIMAL(15,2),
    c2_regular_commitments DECIMAL(15,2),
    c2_discretionary_spending DECIMAL(15,2),
    c2_mortgage_payments DECIMAL(15,2),
    c2_loans_or_credit_cards DECIMAL(15,2),
    c2_other_outgoings DECIMAL(15,2),
    c2_total_outgoings DECIMAL(15,2),
    
    -- Assets (Client 1)
    c1_main_home DECIMAL(15,2),
    c1_second_property DECIMAL(15,2),
    c1_third_property DECIMAL(15,2),
    c1_fourth_property DECIMAL(15,2),
    c1_investments DECIMAL(15,2),
    c1_savings DECIMAL(15,2),
    c1_pension DECIMAL(15,2),
    c1_life_not_in_trust DECIMAL(15,2),
    c1_car_or_boat DECIMAL(15,2),
    c1_chattels DECIMAL(15,2),
    c1_gifts DECIMAL(15,2),
    c1_business_assets DECIMAL(15,2),
    c1_rights_in_trust DECIMAL(15,2),
    c1_expected_inheritance_2y DECIMAL(15,2),
    
    -- Assets (Client 2)
    c2_main_home DECIMAL(15,2),
    c2_second_property DECIMAL(15,2),
    c2_third_property DECIMAL(15,2),
    c2_fourth_property DECIMAL(15,2),
    c2_investments DECIMAL(15,2),
    c2_savings DECIMAL(15,2),
    c2_pension DECIMAL(15,2),
    c2_life_not_in_trust DECIMAL(15,2),
    c2_car_or_boat DECIMAL(15,2),
    c2_chattels DECIMAL(15,2),
    c2_gifts DECIMAL(15,2),
    c2_business_assets DECIMAL(15,2),
    c2_rights_in_trust DECIMAL(15,2),
    c2_expected_inheritance_2y DECIMAL(15,2),
    
    -- Liabilities & Tax
    mortgages_total DECIMAL(15,2),
    loans_total DECIMAL(15,2),
    hp_credit_total DECIMAL(15,2),
    net_assets_total DECIMAL(15,2),
    inheritance_tax_allowance DECIMAL(15,2),
    taxable_estate DECIMAL(15,2),
    inheritance_tax_due DECIMAL(15,2),
    
    -- Beneficiaries
    main_beneficiaries TEXT,
    child_1_name VARCHAR(100),
    child_1_relation_c1 VARCHAR(50),
    child_1_relation_c2 VARCHAR(50),
    child_1_financial_dependency BOOLEAN DEFAULT FALSE,
    child_1_note TEXT,
    child_2_name VARCHAR(100),
    child_2_relation_c1 VARCHAR(50),
    child_2_relation_c2 VARCHAR(50),
    child_2_financial_dependency BOOLEAN DEFAULT FALSE,
    child_2_note TEXT,
    child_3_name VARCHAR(100),
    child_3_relation_c1 VARCHAR(50),
    child_3_relation_c2 VARCHAR(50),
    child_3_financial_dependency BOOLEAN DEFAULT FALSE,
    child_3_note TEXT,
    child_4_name VARCHAR(100),
    child_4_relation_c1 VARCHAR(50),
    child_4_relation_c2 VARCHAR(50),
    child_4_financial_dependency BOOLEAN DEFAULT FALSE,
    child_4_note TEXT,
    child_5_name VARCHAR(100),
    child_5_relation_c1 VARCHAR(50),
    child_5_relation_c2 VARCHAR(50),
    child_5_financial_dependency BOOLEAN DEFAULT FALSE,
    child_5_note TEXT,
    child_6_name VARCHAR(100),
    child_6_relation_c1 VARCHAR(50),
    child_6_relation_c2 VARCHAR(50),
    child_6_financial_dependency BOOLEAN DEFAULT FALSE,
    child_6_note TEXT,
    grandchildren_notes TEXT,
    
    -- Exemptions & Estate Planning
    isa_used_this_year BOOLEAN DEFAULT FALSE,
    atr_risk_result VARCHAR(50),
    atr_in_words TEXT,
    target_capital DECIMAL(15,2),
    current_capital DECIMAL(15,2),
    target_income DECIMAL(15,2),
    excluded_property_trusts BOOLEAN DEFAULT FALSE,
    small_gifts_exemption BOOLEAN DEFAULT FALSE,
    normal_expense_exemption BOOLEAN DEFAULT FALSE,
    lifestyle_trust BOOLEAN DEFAULT FALSE,
    marriage_gift_exemption BOOLEAN DEFAULT FALSE,
    pension_beneficiaries_info TEXT,
    whole_of_life_policy BOOLEAN DEFAULT FALSE,
    inter_vivos_life_cover BOOLEAN DEFAULT FALSE,
    business_property_relief BOOLEAN DEFAULT FALSE,
    agricultural_property_relief BOOLEAN DEFAULT FALSE,
    woodlands_relief BOOLEAN DEFAULT FALSE,
    critical_illness_cover BOOLEAN DEFAULT FALSE,
    private_medical_insurance BOOLEAN DEFAULT FALSE,
    accident_sickness_unemployment_cover BOOLEAN DEFAULT FALSE,
    long_term_care BOOLEAN DEFAULT FALSE,
    savings_scheme BOOLEAN DEFAULT FALSE,
    investments BOOLEAN DEFAULT FALSE,
    pensions BOOLEAN DEFAULT FALSE,
    mortgage_cover BOOLEAN DEFAULT FALSE,
    will_planning_notes TEXT,
    deed_of_variation BOOLEAN DEFAULT FALSE,
    discretionary_trust BOOLEAN DEFAULT FALSE,
    loan_trust BOOLEAN DEFAULT FALSE,
    dual_protection_scheme BOOLEAN DEFAULT FALSE,
    home_protection_scheme BOOLEAN DEFAULT FALSE,
    enterprise_schemes BOOLEAN DEFAULT FALSE,
    
    -- Client Feedback
    feedback_1_solution TEXT,
    feedback_1_benefit TEXT,
    feedback_1_expectation TEXT,
    feedback_2_solution TEXT,
    feedback_2_benefit TEXT,
    feedback_2_expectation TEXT,
    feedback_3_solution TEXT,
    feedback_3_benefit TEXT,
    feedback_3_expectation TEXT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Policies and Valuations table
CREATE TABLE IF NOT EXISTS policies_valuations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    opportunity_id UUID REFERENCES opportunities(id),
    contact_name VARCHAR(100),
    policy_owner VARCHAR(100),
    owner VARCHAR(100),
    product VARCHAR(200),
    policy_register_status VARCHAR(100),
    effective_date DATE,
    received_commission DECIMAL(15,2),
    written_commission DECIMAL(15,2),
    premium_amount DECIMAL(15,2),
    advisor_name VARCHAR(100),
    policy_number VARCHAR(100),
    fund_history TEXT,
    status VARCHAR(50) DEFAULT 'Active',
    
    -- Valuation Details
    valuation_entity VARCHAR(100),
    valuation_date DATE,
    valuation_amount DECIMAL(15,2),
    cash_account_amount DECIMAL(15,2),
    provider_name VARCHAR(100),
    provider_client_number VARCHAR(100),
    income_amount DECIMAL(15,2),
    income_to_date DECIMAL(15,2),
    workflow_status VARCHAR(100),
    email_link_sent BOOLEAN DEFAULT FALSE,
    assigned_to VARCHAR(100),
    
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_leads_owner ON leads(owner);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(current_status);
CREATE INDEX IF NOT EXISTS idx_leads_created ON leads(created_on);

CREATE INDEX IF NOT EXISTS idx_contacts_owner ON contacts(owner);
CREATE INDEX IF NOT EXISTS idx_contacts_status ON contacts(status);
CREATE INDEX IF NOT EXISTS idx_contacts_originating_lead ON contacts(originating_lead);

CREATE INDEX IF NOT EXISTS idx_opportunities_contact_id ON opportunities(contact_id);
CREATE INDEX IF NOT EXISTS idx_opportunities_stage ON opportunities(stage);
CREATE INDEX IF NOT EXISTS idx_opportunities_owner ON opportunities(owner);

CREATE INDEX IF NOT EXISTS idx_factfinds_contact_id ON factfinds(contact_id);
CREATE INDEX IF NOT EXISTS idx_policies_opportunity_id ON policies_valuations(opportunity_id);
