-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.calls (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  lead_first_name character varying,
  lead_phone character varying,
  advisor_name character varying,
  summary text,
  analysis text,
  lead_last_name character varying,
  call_score numeric,
  lead_id uuid,
  advisor_id uuid,
  transcript text,
  CONSTRAINT calls_pkey PRIMARY KEY (id),
  CONSTRAINT calls_advisor_id_fkey FOREIGN KEY (advisor_id) REFERENCES auth.users(id),
  CONSTRAINT calls_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.channel_configurations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  channel_id uuid NOT NULL,
  config_key character varying NOT NULL,
  config_value text,
  is_encrypted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT channel_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT channel_configurations_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.communication_channels(id)
);
CREATE TABLE public.communication_channels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT communication_channels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name character varying,
  last_name character varying,
  salutation character varying,
  email character varying,
  mobile_phone character varying,
  home_phone character varying,
  business_phone character varying,
  fax character varying,
  owner character varying,
  status character varying DEFAULT 'Active'::character varying,
  status_reason text,
  appointment_booked boolean DEFAULT false,
  date_cancelled date,
  review_status character varying,
  review_next_due_date date,
  review_actual_date date,
  review_next_step text,
  review_outcome text,
  reviewed_by character varying,
  review_created_on timestamp without time zone,
  preferred_day character varying,
  preferred_time character varying,
  preferred_service character varying,
  preferred_facility character varying,
  preferred_user character varying,
  allow_email boolean DEFAULT true,
  allow_phone boolean DEFAULT true,
  allow_fax boolean DEFAULT false,
  allow_mail boolean DEFAULT true,
  allow_bulk_email boolean DEFAULT false,
  existing_survey_clarity text,
  existing_survey_helpfulness text,
  existing_survey_advisor_ability text,
  existing_survey_standard text,
  existing_survey_establishment text,
  existing_survey_result character varying,
  potential_survey_literature_useful boolean,
  potential_survey_advice_clear boolean,
  potential_survey_rushed boolean,
  potential_survey_feedback text,
  potential_survey_did_not_go_ahead_reason text,
  address_name character varying,
  street_1 character varying,
  street_2 character varying,
  street_3 character varying,
  city character varying,
  county character varying,
  postal_code character varying,
  country character varying,
  birthday date,
  anniversary date,
  gender character varying,
  spouse_partner_name character varying,
  occupation character varying,
  total_current_value numeric,
  out_of_cash boolean DEFAULT false,
  phase_1_complete boolean DEFAULT false,
  phase_2_complete boolean DEFAULT false,
  phase_3_complete boolean DEFAULT false,
  investment_service_status character varying,
  investment_profile_date date,
  funds_switched boolean DEFAULT false,
  fund_switch_status character varying,
  mps_fee numeric,
  mps_data_input boolean DEFAULT false,
  osf_data_input boolean DEFAULT false,
  originating_lead uuid,
  will_completed boolean DEFAULT false,
  lpa_signed_by_donor boolean DEFAULT false,
  lpa_completed boolean DEFAULT false,
  presentation_consultation_notes text,
  omw_profile_needed boolean DEFAULT false,
  docu_sign_forms_required text,
  docu_sign_sent boolean DEFAULT false,
  email_to_info boolean DEFAULT false,
  send_investment_program boolean DEFAULT false,
  member_service_level character varying,
  client_agreement_signed boolean DEFAULT false,
  risk_level character varying,
  supervising_financial_advisor character varying,
  supporting_broker character varying,
  seminar_invitation_sent boolean DEFAULT false,
  seminar_invitation_date date,
  seminar_attended boolean DEFAULT false,
  google_review_points integer DEFAULT 0,
  trustpilot_points integer DEFAULT 0,
  vouched_for_points integer DEFAULT 0,
  claimed_points integer DEFAULT 0,
  referral_source character varying,
  customer_points_summary text,
  notes text,
  activities text,
  last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_originating_lead_fkey FOREIGN KEY (originating_lead) REFERENCES public.leads(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_id uuid,
  lead_id uuid,
  subject text,
  status character varying DEFAULT 'open'::character varying,
  priority character varying DEFAULT 'medium'::character varying,
  assigned_to uuid,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT conversations_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT conversations_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.factfinds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_id uuid,
  factfind_date date,
  consultant_name character varying,
  owner character varying,
  contact_name character varying,
  currency character varying DEFAULT 'GBP'::character varying,
  reason_for_meeting text,
  c1_title character varying,
  c1_first_name character varying,
  c1_middle_name character varying,
  c1_last_name character varying,
  c1_other_names character varying,
  c1_gender character varying,
  c1_marital_status character varying,
  c1_health_status character varying,
  c1_employment_status character varying,
  c1_occupation character varying,
  c1_dob date,
  c1_smoker boolean DEFAULT false,
  c1_nationality character varying,
  c1_has_will boolean DEFAULT false,
  c1_has_lpa boolean DEFAULT false,
  c1_national_insurance character varying,
  c1_id_type character varying,
  c1_id_number character varying,
  c1_id_country character varying,
  c1_id_expiry date,
  c1_town_of_birth character varying,
  c2_title character varying,
  c2_first_name character varying,
  c2_middle_name character varying,
  c2_last_name character varying,
  c2_other_names character varying,
  c2_gender character varying,
  c2_marital_status character varying,
  c2_health_status character varying,
  c2_employment_status character varying,
  c2_occupation character varying,
  c2_dob date,
  c2_smoker boolean DEFAULT false,
  c2_nationality character varying,
  c2_has_will boolean DEFAULT false,
  c2_has_lpa boolean DEFAULT false,
  c2_national_insurance character varying,
  c2_id_type character varying,
  c2_id_number character varying,
  c2_id_country character varying,
  c2_id_expiry date,
  c2_town_of_birth character varying,
  c1_income numeric,
  c1_council_tax numeric,
  c1_utilities numeric,
  c1_groceries numeric,
  c1_insurances numeric,
  c1_entertainment numeric,
  c1_regular_commitments numeric,
  c1_discretionary_spending numeric,
  c1_mortgage_payments numeric,
  c1_loans_or_credit_cards numeric,
  c1_other_outgoings numeric,
  c1_total_outgoings numeric,
  c2_income numeric,
  c2_council_tax numeric,
  c2_utilities numeric,
  c2_groceries numeric,
  c2_insurances numeric,
  c2_entertainment numeric,
  c2_regular_commitments numeric,
  c2_discretionary_spending numeric,
  c2_mortgage_payments numeric,
  c2_loans_or_credit_cards numeric,
  c2_other_outgoings numeric,
  c2_total_outgoings numeric,
  c1_main_home numeric,
  c1_second_property numeric,
  c1_third_property numeric,
  c1_fourth_property numeric,
  c1_investments numeric,
  c1_savings numeric,
  c1_pension numeric,
  c1_life_not_in_trust numeric,
  c1_car_or_boat numeric,
  c1_chattels numeric,
  c1_gifts numeric,
  c1_business_assets numeric,
  c1_rights_in_trust numeric,
  c1_expected_inheritance_2y numeric,
  c2_main_home numeric,
  c2_second_property numeric,
  c2_third_property numeric,
  c2_fourth_property numeric,
  c2_investments numeric,
  c2_savings numeric,
  c2_pension numeric,
  c2_life_not_in_trust numeric,
  c2_car_or_boat numeric,
  c2_chattels numeric,
  c2_gifts numeric,
  c2_business_assets numeric,
  c2_rights_in_trust numeric,
  c2_expected_inheritance_2y numeric,
  mortgages_total numeric,
  loans_total numeric,
  hp_credit_total numeric,
  net_assets_total numeric,
  inheritance_tax_allowance numeric,
  taxable_estate numeric,
  inheritance_tax_due numeric,
  main_beneficiaries text,
  child_1_name character varying,
  child_1_relation_c1 character varying,
  child_1_relation_c2 character varying,
  child_1_financial_dependency boolean DEFAULT false,
  child_1_note text,
  child_2_name character varying,
  child_2_relation_c1 character varying,
  child_2_relation_c2 character varying,
  child_2_financial_dependency boolean DEFAULT false,
  child_2_note text,
  child_3_name character varying,
  child_3_relation_c1 character varying,
  child_3_relation_c2 character varying,
  child_3_financial_dependency boolean DEFAULT false,
  child_3_note text,
  child_4_name character varying,
  child_4_relation_c1 character varying,
  child_4_relation_c2 character varying,
  child_4_financial_dependency boolean DEFAULT false,
  child_4_note text,
  child_5_name character varying,
  child_5_relation_c1 character varying,
  child_5_relation_c2 character varying,
  child_5_financial_dependency boolean DEFAULT false,
  child_5_note text,
  child_6_name character varying,
  child_6_relation_c1 character varying,
  child_6_relation_c2 character varying,
  child_6_financial_dependency boolean DEFAULT false,
  child_6_note text,
  grandchildren_notes text,
  isa_used_this_year boolean DEFAULT false,
  atr_risk_result character varying,
  atr_in_words text,
  target_capital numeric,
  current_capital numeric,
  target_income numeric,
  excluded_property_trusts boolean DEFAULT false,
  small_gifts_exemption boolean DEFAULT false,
  normal_expense_exemption boolean DEFAULT false,
  lifestyle_trust boolean DEFAULT false,
  marriage_gift_exemption boolean DEFAULT false,
  pension_beneficiaries_info text,
  whole_of_life_policy boolean DEFAULT false,
  inter_vivos_life_cover boolean DEFAULT false,
  business_property_relief boolean DEFAULT false,
  agricultural_property_relief boolean DEFAULT false,
  woodlands_relief boolean DEFAULT false,
  critical_illness_cover boolean DEFAULT false,
  private_medical_insurance boolean DEFAULT false,
  accident_sickness_unemployment_cover boolean DEFAULT false,
  long_term_care boolean DEFAULT false,
  savings_scheme boolean DEFAULT false,
  investments boolean DEFAULT false,
  pensions boolean DEFAULT false,
  mortgage_cover boolean DEFAULT false,
  will_planning_notes text,
  deed_of_variation boolean DEFAULT false,
  discretionary_trust boolean DEFAULT false,
  loan_trust boolean DEFAULT false,
  dual_protection_scheme boolean DEFAULT false,
  home_protection_scheme boolean DEFAULT false,
  enterprise_schemes boolean DEFAULT false,
  feedback_1_solution text,
  feedback_1_benefit text,
  feedback_1_expectation text,
  feedback_2_solution text,
  feedback_2_benefit text,
  feedback_2_expectation text,
  feedback_3_solution text,
  feedback_3_benefit text,
  feedback_3_expectation text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT factfinds_pkey PRIMARY KEY (id),
  CONSTRAINT factfinds_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name character varying,
  last_name character varying,
  salutation character varying,
  email character varying,
  phone_number character varying,
  mobile_phone character varying,
  other_phone character varying,
  verified_phone boolean DEFAULT false,
  verified_email boolean DEFAULT false,
  address text,
  date_of_birth date,
  owner character varying,
  current_status character varying DEFAULT 'Open'::character varying,
  status_reason text,
  current_progress character varying,
  nac_process_stage character varying,
  survey_status character varying,
  survey_date date,
  survey_completed boolean DEFAULT false,
  last_guide_sent timestamp without time zone,
  active_duration_days integer DEFAULT 0,
  created_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  meeting_achievement text,
  goals text,
  budget numeric,
  budget_frequency character varying,
  goal_term character varying,
  goal_year integer,
  household_income numeric,
  property_value numeric,
  mortgage_value numeric,
  savings_investments numeric,
  pension_plans_value numeric,
  car_value numeric,
  contents_value numeric,
  antiques_value numeric,
  bat_value numeric,
  life_insurance_value numeric,
  other_assets_value numeric,
  outstanding_mortgage numeric,
  other_loans_value numeric,
  other_liabilities_value numeric,
  marital_status character varying,
  number_of_children integer,
  will_clause_effect text,
  gifts_last_7_years text,
  gifting_10_percent_estate text,
  iht_score numeric,
  nil_rate_band numeric,
  type_of_lead character varying,
  template_type character varying,
  customer_type character varying,
  lead_source character varying,
  campaign_name character varying,
  last_campaign_date date,
  marketing_materials_sent boolean DEFAULT false,
  added_to_marketing_list boolean DEFAULT false,
  preferred_contact_method character varying,
  allow_email boolean DEFAULT true,
  allow_phone boolean DEFAULT true,
  allow_fax boolean DEFAULT false,
  allow_mail boolean DEFAULT true,
  allow_bulk_email boolean DEFAULT false,
  notes text,
  last_note_by character varying,
  last_note_date timestamp without time zone,
  guides_sent text,
  followup_letter_date date,
  followup_letter_name character varying,
  followup_letter_notes text,
  main_home_beneficiaries text,
  investments_value numeric,
  other_properties_value numeric,
  reason_for_submission text,
  best_time_to_contact text,
  vapi_call_notes text,
  form_submitted timestamp without time zone,
  CONSTRAINT leads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.message_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type character varying,
  file_size integer,
  storage_path text NOT NULL,
  content_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT message_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT message_attachments_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  channel_id uuid NOT NULL,
  direction character varying NOT NULL,
  status character varying NOT NULL,
  subject text,
  body text,
  from_address character varying,
  to_addresses ARRAY,
  cc_addresses ARRAY,
  bcc_addresses ARRAY,
  message_id text,
  thread_id text,
  in_reply_to text,
  has_attachments boolean DEFAULT false,
  metadata jsonb,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.communication_channels(id)
);
CREATE TABLE public.opportunities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_id uuid,
  name character varying NOT NULL,
  description text,
  stage character varying DEFAULT 'Prospecting'::character varying,
  probability integer DEFAULT 0,
  amount numeric,
  expected_close_date date,
  owner character varying,
  source character varying,
  type character varying,
  priority character varying DEFAULT 'Medium'::character varying,
  status character varying DEFAULT 'Open'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  closed_date date,
  notes text,
  CONSTRAINT opportunities_pkey PRIMARY KEY (id),
  CONSTRAINT opportunities_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.policies_valuations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  opportunity_id uuid,
  contact_name character varying,
  policy_owner character varying,
  owner character varying,
  product character varying,
  policy_register_status character varying,
  effective_date date,
  received_commission numeric,
  written_commission numeric,
  premium_amount numeric,
  advisor_name character varying,
  policy_number character varying,
  fund_history text,
  status character varying DEFAULT 'Active'::character varying,
  valuation_entity character varying,
  valuation_date date,
  valuation_amount numeric,
  cash_account_amount numeric,
  provider_name character varying,
  provider_client_number character varying,
  income_amount numeric,
  income_to_date numeric,
  workflow_status character varying,
  email_link_sent boolean DEFAULT false,
  assigned_to character varying,
  created_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT policies_valuations_pkey PRIMARY KEY (id),
  CONSTRAINT policies_valuations_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.opportunities(id)
);
CREATE TABLE public.user_oauth_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider character varying NOT NULL,
  access_token text NOT NULL,
  refresh_token text,
  token_expiry timestamp with time zone,
  email character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_oauth_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT user_oauth_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);